version: 1.0.{build}
before_build:
- git submodule update --init --recursive
- git clone https://github.com/ktxsoftware/nodejs_bin.git
- nodejs_bin\node.exe make.js --kha . --from Tests/Empty --visualstudio vs2013
build:
  project: build\windows-build\Empty.sln
  verbosity: minimal